[package]
org = "@package.org@"
name = "@package.name@"
version = "@package.version@"
distribution = "@ballerina.lang.version@"
authors = ["Ballerina"]
keywords = [
    @package.keywords@,
    "EDI",
    "EDIFACT",
    "@directory.upper@",
    "Vendor/Other",
    "Area/ERP & Business Operations",
    "Type/Library",
    "Name/@package.display.name@"
]
repository = "https://github.com/ballerina-platform/module-ballerinax-edifact"
license = ["Apache-2.0"]
